Repository PenguinOfWar/strapi-plugin-paper-trail, pull requests merged in 2024-02, with the labels that each got.

#15 Fix Undefined Bug from Admin console
  admin/src/components/PaperTrail/PaperTrail.js
  package.json
Labels: bug

#16 feat: Adding raw JSON view from #13, adding eslint, updating components to comply with eslint rules, fixing hook violations
  .eslintrc.json
  .github/workflows/unit-test.yml
  .nova/Tasks/Node.json
  admin/src/components/MediaCard/MediaCard.js
  admin/src/components/PaperTrail/PaperTrail.js
  admin/src/components/PaperTrailReview/PaperTrailReview.js
  admin/src/components/PaperTrailViewer/PaperTrailViewer.js
  admin/src/components/RenderField/RenderField.js
  admin/src/components/RevisionForm/RevisionForm.js
  admin/src/components/TrailTable/TrailTable.js
  admin/src/components/TrailsTablePagination/TrailsTablePagination.js
  admin/src/index.js
  admin/src/translations/en.json
  admin/src/translations/pt-BR.json
  admin/src/utils/buildPayload.js
  package-lock.json
  package.json
  server/bootstrap.js
  server/config/index.js
  server/content-types/index.js
  server/content-types/trail/index.js
  server/destroy.js
  server/index.js
  server/middlewares/index.js
  server/register.js
  server/services/index.js
  server/services/paper-trail.js
  server/utils/getContentTypeSchema.js
  server/utils/prepareTrailFromSchema.js
  yarn.lock
Labels: enhancement

#19 task: improving support for single types while trying to replicate #17
  README.md
  admin/src/components/PaperTrail/PaperTrail.js
  admin/src/components/PaperTrailViewer/PaperTrailViewer.js
  package-lock.json
  package.json
  server/utils/getPathParams.js
  server/utils/matchAdminPath.js
  tests/getPathParms.test.js
  tests/matchAdminPath.test.js
Labels: bug, enhancement
